name: gotip

on:
  schedule:
    - cron: '11 * * * *'

jobs:
  gotip:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -yq golang pixz bzip2
      - name: Clone
        run: |
          git clone --depth=1 https://go.googlesource.com/go
          sudo mv go /opt/
      - name: Make
        run: |
          cd /opt/go/src
          ./make.bash
      - name: Tarball
        run: |
          cd /opt
          tar -Ipixz -cf /tmp/gotip.linux-amd64.tar.xz go
      - name: Release
        run: |
          curl -L https://github.com/github-release/github-release/releases/download/v0.9.0/linux-amd64-github-release.bz2 | bzip2 -d >github-release
          chmod +x github-release && sudo mv github-release /usr/bin/
          github-release delete -s ${GOTIP_TOKEN} -u phuslu -r gotip -t v0.0.0 || true
          github-release release -s ${GOTIP_TOKEN} -u phuslu -r gotip -t v0.0.0 --target master
          github-release -v upload -s ${GOTIP_TOKEN} -u phuslu -r gotip -t v0.0.0 \
              -n gotip.linux-amd64.tar.xz -f /tmp/gotip.linux-amd64.tar.xz
        env:
          GOTIP_TOKEN: ${{ secrets.GOTIP_TOKEN }}
