name: update

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          git clone https://${IPLIST_TOKEN}@github.com/${GITHUB_REPOSITORY}
          cd $(basename ${GITHUB_REPOSITORY})
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          bash -xe .update.bash
        env:
          IPLIST_TOKEN: ${{ secrets.IPLIST_TOKEN }}
