name: update

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          git clone https://${IPLIST_TOKEN}@github.com/${GITHUB_REPOSITORY}
          wget -N -O delegated-apnic-latest http://ftp.apnic.net/stats/apnic/delegated-apnic-latest
          cd apnic-iplist
          for geotxt in $(ls ??.txt); do
             cat ../delegated-apnic-latest | \
             grep -i "^apnic|${geotxt%.*}|ipv4|" | \
             awk -F'|' '{printf("%s/%d\n", $4, 32-log($5)/log(2))}' | \
             ./cidrmerge > ${geotxt}
          done
          git add *.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git commit -m "update iplist" -a; then
            git push origin master
          fi
          true
        env:
          IPLIST_TOKEN: ${{ secrets.IPLIST_TOKEN }}
