name: gotip

on:
  schedule:
    - cron: '50 * * * *'

jobs:
  gotip:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -yq golang pixz bzip2
      - name: Clone
        run: |
          git clone --depth=1 https://go.googlesource.com/go
          sudo mv go /opt/
      - name: Make
        run: |
          cd /opt/go/src
          ./make.bash
      - name: Tarball
        run: |
          cd /opt
          tar -Ipixz -cvf /tmp/gotip.linux-amd64.tar.xz go
      - name: Release
        run: |
          export GITHUB_TOKEN=${GOTIP_TOKEN}
          curl -L https://github.com/github-release/github-release/releases/download/v0.9.0/linux-amd64-github-release.bz2 | bzip2 -d >github-release
          chmod +x github-release
          ./github-release -v upload --replace \
              --user phuslu --repo gotip \
              --tag v0.0.0 --name gotip.linux-amd64.tar.xz \
              --file /tmp/gotip.linux-amd64.tar.xz
        env:
          GOTIP_TOKEN: ${{ secrets.GOTIP_TOKEN }}
